# Generated by Django 4.2.1 on 2023-05-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_text', models.CharField(max_length=200)),
                ('begining_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itprogress.technology')),
            ],
        ),
    ]
